run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly


linters:
  disable-all: true
  enable:
    # статические проверки
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - unparam
    - nilerr
    - prealloc

    # стиль
    - gofmt
    - misspell
    - nakedret

    # сложность
    - gocyclo
    - gocognit

    # loopvar fix for Go 1.22+
    - copyloopvar

linters-settings:
  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 20

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/your-org/your-project

  revive:
    severity: warning
    rules:
      - name: exported
      - name: indent-error-flow
      - name: error-naming
      - name: var-naming
      - name: package-comments
      - name: receiver-naming

issues:
  exclude-dirs:
    - research
    - internal/delivery/http
    - internal/delivery/web
    - internal/delivery/cli
    - cmd

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

