version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ppo_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ppo
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ppo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    container_name: ppo_mongo
    ports:
      - "27017:27017"
    volumes:
      - ppo_mongo_data:/data/db
      - ./mongo-migrations:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: myappdb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  minio:
    image: quay.io/minio/minio
    container_name: ppo_minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ppo_minio_data:/data

volumes:
  ppo_pg_data:
  ppo_mongo_data:
  ppo_minio_data: